(* Generate TypeScript type definitions *)

let generate (file : Ast.file) : string =
  let buf = Buffer.create 4096 in
  let line s = Buffer.add_string buf s; Buffer.add_char buf '\n' in
  let blank () = Buffer.add_char buf '\n' in

  line "// Auto-generated by Vessel — do not edit";
  blank ();

  (* Branded ID types for all *Ref occurrences *)
  let refs = Emitter.collect_ref_types file in
  List.iter (fun name ->
    let id = Emitter.ref_id name in
    line (Printf.sprintf "export type %s = string & { readonly __brand: \"%s\" }" id id)
  ) refs;
  if refs <> [] then blank ();

  (* Const declarations *)
  let rec lit_to_ts = function
    | Ast.Lit_string s -> "\"" ^ s ^ "\""
    | Ast.Lit_int i -> string_of_int i
    | Ast.Lit_float f -> string_of_float f
    | Ast.Lit_bool b -> string_of_bool b
    | Ast.Lit_array xs -> "[" ^ String.concat ", " (List.map lit_to_ts xs) ^ "]"
  in

  List.iter (function
    | Ast.Const c ->
      let kw = match c.value with
        | Ast.Lit_array _ -> "const"
        | _ -> "const"
      in
      line (Printf.sprintf "export %s %s = %s as const" kw c.name (lit_to_ts c.value));
      blank ()
    | _ -> ()
  ) file.declarations;

  (* Struct → interface *)
  List.iter (function
    | Ast.Struct s ->
      line (Printf.sprintf "export interface %s {" s.name);
      List.iter (fun (f : Ast.field) ->
        let opt = if f.optional then "?" else "" in
        line (Printf.sprintf "  %s%s: %s" f.name opt (Emitter.ts_type f.typ))
      ) s.fields;
      line "}";
      blank ()
    | _ -> ()
  ) file.declarations;

  (* Enum → string union *)
  List.iter (function
    | Ast.Enum e ->
      let members = List.map (fun (m : Ast.enum_member) ->
        Printf.sprintf "  | \"%s\"" m.name
      ) e.members in
      line (Printf.sprintf "export type %s =" e.name);
      List.iter line members;
      blank ()
    | _ -> ()
  ) file.declarations;

  (* Union → type union *)
  List.iter (function
    | Ast.Union u ->
      let variants = List.map Emitter.ts_type u.variants in
      line (Printf.sprintf "export type %s = %s" u.name (String.concat " | " variants));
      blank ()
    | _ -> ()
  ) file.declarations;

  (* Service → handler interface *)
  List.iter (function
    | Ast.Service s ->
      line (Printf.sprintf "export interface %sHandlers {" s.name);
      List.iter (fun (m : Ast.method_decl) ->
        let params = List.map (fun (p : Ast.param) ->
          p.name ^ ": " ^ Emitter.ts_type p.typ
        ) m.params in
        let ret = Emitter.ts_type m.return_type in
        let raises_comment = match m.raises with
          | [] -> ""
          | rs -> " // throws " ^ String.concat " | " rs
        in
        line (Printf.sprintf "  %s(%s): Promise<%s>%s"
          m.name (String.concat ", " params) ret raises_comment)
      ) s.methods;
      line "}";
      blank ()
    | _ -> ()
  ) file.declarations;

  Buffer.contents buf
