(* Generate Zod validation schemas *)

let generate (file : Ast.file) : string =
  let buf = Buffer.create 4096 in
  let line s = Buffer.add_string buf s; Buffer.add_char buf '\n' in
  let blank () = Buffer.add_char buf '\n' in

  line "// Auto-generated by Vessel — do not edit";
  line "import { z } from \"zod\"";
  blank ();

  (* Branded ID schemas *)
  let refs = Emitter.collect_ref_types file in
  List.iter (fun name ->
    let id = Emitter.ref_id name in
    line (Printf.sprintf "export const %sSchema = z.string().brand(\"%s\")" id id)
  ) refs;
  if refs <> [] then blank ();

  (* Struct → z.object *)
  List.iter (function
    | Ast.Struct s ->
      line (Printf.sprintf "export const %sSchema = z.object({" s.name);
      List.iter (fun (f : Ast.field) ->
        let zt = Emitter.zod_type f.typ in
        let zt = if f.optional then zt ^ ".optional()" else zt in
        line (Printf.sprintf "  %s: %s," f.name zt)
      ) s.fields;
      line "})";
      blank ()
    | _ -> ()
  ) file.declarations;

  (* Enum → z.enum *)
  List.iter (function
    | Ast.Enum e ->
      let members = List.map (fun (m : Ast.enum_member) ->
        "\"" ^ m.name ^ "\""
      ) e.members in
      line (Printf.sprintf "export const %sSchema = z.enum([%s])"
        e.name (String.concat ", " members));
      blank ()
    | _ -> ()
  ) file.declarations;

  (* Union → z.union *)
  List.iter (function
    | Ast.Union u ->
      let schemas = List.map (fun t -> Emitter.zod_type t) u.variants in
      line (Printf.sprintf "export const %sSchema = z.union([%s])"
        u.name (String.concat ", " schemas));
      blank ()
    | _ -> ()
  ) file.declarations;

  (* Service request/response schemas *)
  List.iter (function
    | Ast.Service s ->
      List.iter (fun (m : Ast.method_decl) ->
        if m.params <> [] then begin
          line (Printf.sprintf "export const %s_%sRequestSchema = z.object({" s.name m.name);
          List.iter (fun (p : Ast.param) ->
            line (Printf.sprintf "  %s: %s," p.name (Emitter.zod_type p.typ))
          ) m.params;
          line "})";
          blank ()
        end
      ) s.methods
    | _ -> ()
  ) file.declarations;

  Buffer.contents buf
